name: hippo_ui_flutter
description: Flutter widget preview annotations for Hipposphere UI tooling.
version: 0.1.3
homepage: https://hippolabs.org
publish_to: "https://pub.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  hippo_ui:
    hosted: https://pub.hippolabs.org/pub/internal-pub/
    version: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
