name: hippo_ui_flutter
description: Flutter widget preview annotations for Hipposphere UI tooling.
version: 0.1.7
homepage: https://hippolabs.org
publish_to: "https://pub.hippolabs.org"
resolution: workspace

environment:
  sdk: ">=3.13.0 < 4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  hippo_ui:
    hosted: https://pub.hippolabs.org
    version: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
