name: hippo_zstandard
description: Cross-platform Zstandard compression backed by Rust native assets and WebAssembly.
version: 0.1.0
homepage: https://hippolabs.org
publish_to: "https://pub.hippolabs.org"
resolution: workspace

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  code_assets: ^1.2.1
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  hooks: ^2.1.0
  native_toolchain_rust: ^1.0.4+0
  web: ^1.1.1

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  hippo_analysis:
    hosted: https://pub.hippolabs.org
    version: ^0.1.2

flutter:
  assets:
    - web/hippo_zstandard.wasm
    - web/hippo_zstandard_worker.js
