name: hippo_ui_jaspr
description: Jaspr widget preview annotations for Hipposphere UI tooling. - WIP
version: 0.1.1
homepage: https://hippolabs.org
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.13.0 < 4.0.0"

dependencies:
  hippo_ui:
    hosted: https://pub.hippolabs.org
    version: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
