builders:
  json_schema:
    import: "package:json_schema_gen/builder.dart"
    builder_factories: ["jsonSchemaBuilder"]
    build_extensions: {".dart": [".json_schema.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
