name: hippo_core_flutter
description: Flutter bindings and storage implementations for hippo_core primitives.
version: 0.1.13
homepage: https://hippolabs.org
publish_to: "https://pub.hippolabs.org"
resolution: workspace

environment:
  sdk: ">=3.13.0 < 4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  hippo_core:
    hosted: https://pub.hippolabs.org
    version: ^0.1.9
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
