name: hippobase_auth_flutter
description: Flutter integration widgets for Hippobase Auth.
version: 0.1.1
homepage: https://hippolabs.org
publish_to: "https://pub.hippolabs.org"
resolution: workspace

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  dart_edge_core:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.35
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^5.0.3
  hippo_core:
    hosted: https://pub.hippolabs.org
    version: ^0.1.5
  hippo_core_flutter:
    hosted: https://pub.hippolabs.org
    version: ^0.1.6
  hippobase_auth_client:
    hosted: https://pub.hippolabs.org
    version: ^0.1.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
