name: hippobase_storage_models
description: Shared Hippobase storage value objects.
version: 0.1.2
homepage: https://hippolabs.org
publish_to: "https://pub.hippolabs.org"
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dev_dependencies:
  test: ^1.30.0
