name: hippobase_auth_server
description: Server package for Hippobase Auth.
version: 0.1.0
homepage: https://hippolabs.org
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"
